/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.ing.sis.ofertaLaboral.vista;

import javax.swing.JPanel;

/**
 *
 * @author nico_
 */
public class Principal extends javax.swing.JFrame {
    private Menu menu;
    private AgregarProducto agregar;
    private ModificarProducto modificar;
    private EliminarProducto eliminar;
    private AgregarVenta agregarV;
    private ListaProductos lista;
    private ListaVentas lista2;
    /**
     * Creates new form Principal
     */
    public Principal() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Bienvenidos a nuestra Panaderia");
        setResizable(false);
        setIconImage(getIconImage());
        iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void iniciar() {
        menu = new Menu(this);
        menu.setVisible(true);
        add(menu);
        pack();
        setLocationRelativeTo(null);
    }
    void irAgregar(JPanel jPanel) {
        setTitle("Agregue un producto a la vez,Gracias");
        remove(jPanel);
        agregar = new AgregarProducto(this);
        agregar.setVisible(true);
        add(agregar);
        pack();
        setLocationRelativeTo(null);
    }
    
        void irAModificar(JPanel jPanel) {
        setTitle("Tenga precaucion al modificar el productos");
        remove(jPanel);
        modificar = new ModificarProducto(this);
        modificar.setVisible(true);
        add(modificar);
        pack();
        setLocationRelativeTo(null);
    }
        void irAEliminar(JPanel jPanel) {
        setTitle("Digite el id del producto a eliminar");
        remove(jPanel);
        eliminar = new EliminarProducto(this);
        eliminar.setVisible(true);
        add(eliminar);
        pack();
        setLocationRelativeTo(null);
    }
        void irAgregarV(JPanel jPanel) {
        setTitle("Tenga cuidado con los registros");
        remove(jPanel);
        agregarV = new AgregarVenta(this);
        agregarV.setVisible(true);
        add(agregarV);
        pack();
        setLocationRelativeTo(null);
    }
      void volver(JPanel jPanel) {
        remove(jPanel);
        menu = new Menu(this);
        menu.setVisible(true);
        add(menu);
        pack();
        setLocationRelativeTo(null);
    } 
       void irVerP(JPanel jPanel) {
        
        remove(jPanel);
        lista = new ListaProductos(this);
        lista.setVisible(true);
        add(lista);
        pack();
        setLocationRelativeTo(null);
    }
        void irAReporte(JPanel jPanel) {
       
        remove(jPanel);
        lista2 = new ListaVentas(this);
        lista2.setVisible(true);
        add(lista2);
        pack();
        setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
